booking/urls.py
from django.conf.urls import patterns, url
from .views import *


urlpatterns = patterns('',
                       url(r'^$', BookingView.as_view(), name='home'),
                       url(r'^new/$', Booking2View.as_view(), name='new'),
                       url(r'^new/data/$', Booking2DataView.as_view(), name='new_data'),
                       url(r'^success/(?P<pk>\d+)/$', BookingSuccessView.as_view(), name='success'),
                       url(r'^cancel/(?P<pk>\d+)/(?P<public_key>\w+)/$', BookingCancelView.as_view(), name='cancel'),
                       )

events/urls.py
from django.conf.urls import patterns, url
from .views import EventDetailView

urlpatterns = patterns('',
                       url(r'^$', 'events.views.home', name='home'),
                       url(r'^(?P<code>promotions)/$', 'events.views.event_filter', name='event_filter'),
                       url(r'^(?P<code>regional)/$', 'events.views.event_filter', name='event_filter'),
                       url(r'^(?P<code>past)/$', 'events.views.event_filter', name='event_filter'),
                       url(r'^(?P<slug>\w+)/$', EventDetailView.as_view(), name='detail'),
                       )

lekotti/urls.py
from lekotti import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from .sitemap import sitemaps
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
admin.autodiscover()

import object_tools
object_tools.autodiscover()


urlpatterns = i18n_patterns('',
                            url(r'^gallery/', include('gallery.urls', namespace='gallery')),
                            url(r'^booking/', include('booking.urls', namespace='booking')),
                            url(r'^activity/', include('activity.urls', namespace='activity')),
                            url(r'^interesting/', include('interesting.urls', namespace='interesting')),
                            url(r'^services/', include('services.urls', namespace='services')),
                            url(r'^events/', include('events.urls', namespace='events')),
                            url(r'^ski_slope/worktime/', 'skislope.views.worktime', name='ski_slope_worktime'),
                            url(r'^bus_schedule/(?P<month>\d{2})/(?P<day>\d{2})/(?P<year>\d{4})/',
                                'contact.views.bus_schedule', name='bus_schedule'),
                            url(r'^admin/help/', include('admin_help.urls', namespace='help')),
                            )


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^admin/translate/', include('rosetta.urls')),
                            )


urlpatterns += patterns('',
                        url(r'^admin_tools/', include('admin_tools.urls')),
                        url(r'^cked/', include('cked.urls')),
                        url(r'^lang/(?P<code>[a-z]{2})/$', 'main.views.lang', name='lang'),
                        url(r'^accounts/profile/', 'main.views.login_success'),
                        url(r'^accounts/', include('allauth.urls')),
                        # url(r'^accounts/profile/', RedirectView.as_view(url='/')),
                        url(r'^logout/', 'main.views.user_logout', name='logout'),
                        # url(r'', include('social_auth.urls')),
                        )
urlpatterns += i18n_patterns('',
                             url(r'^admin/', include(admin.site.urls)),
                             )


urlpatterns += patterns('',
                        (r'^%s(.*)$' % settings.STATIC_URL[1:],
                         'django.views.static.serve',
                         {'document_root': settings.STATIC_ROOT}),
                        )
urlpatterns += patterns('',
                        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve',
                         {"document_root": settings.MEDIA_ROOT}),
                        )


if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^404/$', TemplateView.as_view(template_name='404.html')),
                            url(r'^500/$', TemplateView.as_view(template_name='500.html')),
                            )


urlpatterns += patterns('',
                        url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
                        url(r'^robots\.txt$', 'main.views.robots')
                        )

urlpatterns += i18n_patterns('',
                             (r'^(?P<url>.*)$', 'main.views.extend_flatpage'),
                             )

urlpatterns += patterns('',
                        (r'^object-tools/', include(object_tools.tools.urls)),
                        )

booking/models.py
from django.db import models
from django.utils.translation import pgettext_lazy, ugettext_lazy as _
from django_resized import ResizedImageField
from cked.fields import RichTextField
from datetime import timedelta
from django.core.urlresolvers import reverse
import random
import hashlib


class AccommodationType(models.Model):
    name = models.CharField(_('name'), max_length=256)
    object_number = models.PositiveSmallIntegerField(_('object number'), default=1)
    guests_number = models.PositiveSmallIntegerField(_('max number of guests'), default=1)
    adults_number = models.PositiveSmallIntegerField(_('max number of adults'), default=1)
    photo = ResizedImageField(_('photo'), upload_to="booking", max_width=1600, max_height=1200)
    ordering = models.IntegerField(_('ordering'), default=100)
    description = RichTextField(_('description'), blank=True, null=True)
    default_price = models.PositiveSmallIntegerField(_('default price'), default=100, help_text=_('in Euros'))

    def __unicode__(self):
        return self.name

    def object_number_variants(self):
        return range(1, self.object_number+1)

    class Meta:
        ordering = ['ordering']
        verbose_name = _('accommodation type')
        verbose_name_plural = _('accommodation types')


class AdditionalOption(models.Model):
    slug = models.SlugField(_('code'), help_text=_('for use in program code'))
    name = models.CharField(_('name'), max_length=256)
    description = RichTextField(_('description'), blank=True, null=True)
    accommodation_type = models.ManyToManyField(AccommodationType, related_name='accommodation type', blank=True,
                                                null=True)
    active_from = models.DateField(_('active from'), blank=True, null=True)
    active_to = models.DateField(_('active to'), blank=True, null=True)
    ordering = models.IntegerField(_('ordering'), default=100)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['ordering']
        verbose_name = _('additional option')
        verbose_name_plural = _('additional options')


class PaymentTerm(models.Model):
    slug = models.SlugField(_('code'), help_text=_('for use in program code'))
    name = models.CharField(_('name'), max_length=256)
    description = RichTextField(_('description'), blank=True, null=True)
    ordering = models.IntegerField(_('ordering'), default=100)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['ordering']
        verbose_name = _('payment term')
        verbose_name_plural = _('payment terms')


class Booking(models.Model):
    add_time = models.DateTimeField(_('add time'), auto_now_add=True)
    acc_type = models.ForeignKey(AccommodationType, verbose_name=_('accommodation type'))
    object_number = models.PositiveSmallIntegerField(_('object number'), default=1)
    date_check_in = models.DateField(_('date check in'))
    date_check_out = models.DateField(_('date check out'))
    adults = models.PositiveSmallIntegerField(_('adults'), default=1)
    children = models.PositiveSmallIntegerField(_('children'), default=0)
    extra_options = models.ManyToManyField(AdditionalOption,
                                           verbose_name=_('additional options'), blank=True, null=True)
    payment_terms = models.ManyToManyField(PaymentTerm, verbose_name=_('payment terms'), blank=True, null=True)
    price = models.FloatField(_('price'), blank=True, null=True)
    name = models.CharField(_('name'), max_length=512)
    email = models.EmailField(_('email'))
    phone = models.CharField(_('phone'), max_length=32)
    check_in_time = models.CharField(_('check in time'), max_length=128, null=True, blank=True)
    note = models.TextField(_('note'), blank=True)

    private_key = models.CharField(max_length=64, default=random.getrandbits(64), null=True, blank=True)

    cancelled = models.BooleanField(_('cancelled'), default=False)

    def __unicode__(self):
        return u'%s (%s - %s)' % (self.name, self.date_check_in, self.date_check_out)

    def get_public_key(self):
        hash_source = '|'.join([
            u'%s' % self.id,
            u'%s' % self.add_time,
            u'%s' % self.private_key
        ])
        return hashlib.md5(hash_source).hexdigest().upper()

    def test_key(self, key):
        return self.get_public_key() == key

    def get_cancel_url(self):
        return reverse('booking:cancel', args=[str(self.id), self.get_public_key()])

    class Meta:
        verbose_name = _('booking order')
        verbose_name_plural = _('booking orders')
        ordering = ['-add_time']


class RateCard(models.Model):
    name = models.CharField(_('name'), max_length=255, unique=True)
    nights_count = models.PositiveSmallIntegerField(_('min count of nights'), default=1)
    acc_type = models.ForeignKey(AccommodationType, verbose_name=_('accommodation type'))
    conditions = models.ForeignKey(PaymentTerm)
    description = models.TextField(_('description'), blank=True)

    def __unicode__(self):
        return u'%s' % self.name

    def get_description(self):
        return u'%s | %s | %s %s' % \
               (self.acc_type, self.conditions, self.nights_count, pgettext_lazy('rate card', 'nights'))

    def get_full_description(self):
        return u'%s (%s)' % (self.__unicode__(), self.get_description())

    class Meta:
        ordering = ['nights_count']
        verbose_name = _('rate card far single days')
        verbose_name_plural = _('rate cards far single days')


class PackagePriceList(models.Model):
    name = models.CharField(_('name'), max_length=512)
    acc_type = models.ForeignKey(AccommodationType, verbose_name=_('accommodation type'))
    conditions = models.ForeignKey(PaymentTerm, verbose_name=_('conditions'))
    description = models.TextField(_('description'), blank=True)

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('rate card (for packages)')
        verbose_name_plural = _('rate cards (for packages)')


class BookingPrice(models.Model):
    rate_card = models.ForeignKey(RateCard, verbose_name=_('rate card'))
    date = models.DateField(_('date'))
    price = models.PositiveIntegerField(_('price'), null=True)

    def __unicode__(self):
        return ''

    def get_rate_card_description(self):
        return u'%s' % self.rate_card.get_description()

    class Meta:
        verbose_name = _('price for separate day')
        verbose_name_plural = _('prices for separate days')
        ordering = ['date']


class BookingPackagePrice(models.Model):
    price_list = models.ForeignKey(PackagePriceList)
    date_check_in = models.DateField(_('date check in'))
    date_check_out = models.DateField(_('date check out'))
    price = models.PositiveIntegerField(_('price'), null=True, blank=True)

    def get_price(self):
        if self.price:
            return self.price
        else:
            price = 0
            days_count = int((self.date_check_out - self.date_check_in).days)
            for n in range(days_count):
                d = self.date_check_in + timedelta(n)
                s_price = BookingPrice.objects.filter(
                    rate_card__acc_type=self.price_list.acc_type,
                    date=d,
                    rate_card__nights_count__lte=days_count
                ).order_by('-rate_card__nights_count').first()
                if s_price:
                    price += s_price.price
                else:
                    return None
            return price
    get_price.short_description = _('price calculated')

    def get_days(self):
        return (self.date_check_out - self.date_check_in).days

    def __unicode__(self):
        return ''

    class Meta:
        verbose_name = _('package offer price')
        verbose_name_plural = _('package offer prices')
        ordering = ['date_check_in']

booking/forms.py
from django import forms
from .models import Booking
from django.utils.translation import ugettext_lazy as _


class BookingAddForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BookingAddForm, self).__init__(*args, **kwargs)
        self.fields['acc_type'].empty_label = ''

    class Meta:
        model = Booking
        exclude = ['private_key', 'cancelled']
        widgets = {
            'object_number': forms.Select(),
            'adults': forms.HiddenInput(),
            'children': forms.HiddenInput(),
            'extra_options': forms.CheckboxSelectMultiple(),
        }


class BookingPriceImportForm(forms.Form):
    file = forms.FileField(label=_('File CSV'))


class BookingCancelForm(forms.ModelForm):
    public_key = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(BookingCancelForm, self).__init__(*args, **kwargs)
        self.fields['public_key'].initial = kwargs['instance'].get_public_key()

    class Meta:
        model = Booking
        fields = []

booking/templates/booking/booking2.html
{% extends "booking/booking_base.html" %}
{% load staticfiles i18n widget_tweaks %}
{% block content %}

    <div class="container booking2" ng-app="bookingApp">
    <div ng-controller="bookingController">
    <form action="{% url "booking:new" %}" id="booking_form" method="post">
    {% csrf_token %}




        <div class="tabla">
            <calendario></calendario>
            <div class="form_clear_block">
                <div class="form_clear_button" ng-click="result_init()">{% trans "Reset form" %}</div>
            </div>
            {% verbatim %}
            <ul class="lista_de_los_tipos_de_alojamiento">
                <li
                        ng-repeat="acc_type in acc_types"
                        ng-class="{true:'active', false:''}[result.accType==acc_type.id]"
                        ng-click="set_acc_type_selected_id(acc_type.id)"
                        >
                    <img ng-src="/media/{{ acc_type.photo }}" class="foto">
                    <h5 class="titulo">
                        <span class="vert">
                            <span
                                    class="linea"
                                    ng-click="showAccTypeDescription(acc_type.id)"
                                    >{{ acc_type.name }}</span>
                        </span>
                    </h5>
                    <div class="descripcion_del_alojamiento"></div>
                    <select
                            ui-select2="select2Options"
                            ng-model="acc_type['object_number_selected']"
                            ng-change="bedsRecount()"
                            class="numero">
                         <option ng-repeat="q in acc_type['object_number_range']">{{ q }}</option>
                    </select>
                </li>
            </ul>
            {% endverbatim %}
        </div>










    <h3>{% trans "Parameters of accommodation" %}</h3>
    <div class="parameters_of_accommodation">
        <div class="type_of_apartments dh">
            <div class="lh">
                <label class="message">выберете тип размещения</label>
            </div>

            {{ form.acc_type|add_class:"acc_type-select"|attr:"ui-select2:select2Options"|attr:"ng-model:result.accType" }}
            <select
                    class="number-select"
                    id="id_object_number"
                    name="object_number"
                    ui-select2="select2Options"
                    ng-model="acc_types[result.accType].object_number_selected"
                    ng-disabled="result.accType==0"
                    >
                {% verbatim %}
                <option ng-repeat="number in acc_types[result.accType].object_number_range" value="{{ number }}">{{ number }}</option>
                {% endverbatim %}
            </select>
        </div>
        <div class="dates_of_living dh">
            {{ form.date_check_in|add_class:"form-control date check-in"|attr:"ui-date:dateOptions"|attr:"ng-model:checkInDate" }}
            {{ form.date_check_out|add_class:"form-control date check-out"|attr:"ui-date:dateOptions"|attr:"ng-model:checkOutDate" }}
            <div class="lh">
                <label class="message">выберете дату заезда</label>
            </div>
        </div>
        <div class="type_of_living">
            <label>{% trans "Adults" %}</label>
            <select class="adults-select" id="adults-select" name="adults" disabled></select>
            {{ form.adults }}

            <label>{% trans "Children" %}</label>
            <select class="children-select" id="children-select" name="children" disabled></select>
            {{ form.children }}

            <div class="lh">
                <label class="message">выберете количество взрослых</label>
            </div>
        </div>
    </div>



    <div class="terms">
        <div class="options">
            <h3>{% trans "More options" %}</h3>
{% for option in options %}
            <div class="terms_item">
                <input type="checkbox"
                       name="extra_options"
                       class="extra_option_checkbox"
                       value="{{ option.id }}">
                <a class="term_title valor popup_link" href="#option_{{ option.id }}">{{ option.name }}</a>
                <div class="term_description-wrap">
                    <div class="term_description" id="option_{{ option.id }}">
                        <h4>{{ option.name }}</h4>
                        {{ option.description|safe }}
                    </div>
                </div>
            </div>
{% endfor %}
        </div>
        <div class="payment">
            <h3>{% trans "Payment and Cancellation" %}</h3>
{% for payment_term in payment_terms %}
            <div class="payment_item">
                <input type="radio"
                       name="payment_terms"
                       class="payment_terms_rb"
                       value="{{ payment_term.id }}"{% if forloop.first %} checked{% endif %}>
                <span class="payment_item_label valor">{{ payment_term.name }}</span>
                <div class="description">
                    <div class="description-text">{{ payment_term.description }}</div>
                    <span class="turn">Свернуть</span>
                </div>
            </div>
{% endfor %}
        </div>
    </div>
    {% verbatim %}
    {{ result }}
    {% endverbatim %}


    <div class="entrada">
        <h1>Ввод данных</h1>
        <div class="slogan">Мы предоставляем свои услуги совершенно бесплатно, так как в отличие от многих других компаний, мы не взимаем плату за нашу работу и не прибавляем дополнительные сборы (за оформление бронирования) к стоимости номера.</div>
        <div class="datos_personales">
            <div class="personale form-group">
                <div class="lh"><label class="message">Поле обязательно для заполнения</label></div>
                {{ form.name|add_class:"form-control required"|attr:"placeholder:ФИО *" }}
            </div>
            <div class="personale form-group">
                <div class="lh">
                    <label class="message">Поле обязательно для заполнения</label>
                    <label class="message special">Введите правильный email</label>
                </div>
                {{ form.email|add_class:"form-control email required"|attr:"placeholder:E-mail *" }}
            </div>
            <div class="personale form-group">
                <div class="lh"><label class="message">Поле обязательно для заполнения</label></div>
                {{ form.phone|add_class:"form-control required"|attr:"placeholder:Мобильный телефон *" }}
            </div>
            <div class="personale form-group">
                {{ form.check_in_time|add_class:"form-control"|attr:"placeholder:Предварительное время заезда" }}
            </div>
            <div class="personale form-group">
                {{ form.note|add_class:"form-control"|attr:"placeholder:Дополнительные сведения"|attr:"rows:" }}
            </div>
            <div class="form-note">Пункты, помеченные «*» обязательны к заполнению.</div>

        </div>
        <div class="condiciones_seleccionadas">
            <div class="seleccionado alojamiento" ng-show="result.accType > 0">
                <label>Тип размещения:</label>
                <div class="valor" id="cs_tipo">{% verbatim %}{{ acc_types[result.accType].name }}{% endverbatim %}</div>
            </div>
            <div class="seleccionado period"
                 ng-show="result.dates.checkIn.isValid() || result.dates.checkOut.isValid()"
                    >
                <label>Период размещения:</label>
                <div class="valor">{% verbatim %}
                    <span ng-show="result.dates.checkIn.isValid()">c {{ result.dates.checkIn|dateFormat }}</span>
                    <span ng-show="result.dates.checkOut.isValid()">по {{ result.dates.checkOut|dateFormat }}</span>
                    <span class="que">
                        <span ng-show="result.places.adult">{{ result.places.adult }} взрослых<span ng-show="result.places.children">,</span></span>
                        <span ng-show="result.places.children">{{ result.places.children }} детский</span>
                    </span>
                {% endverbatim %}</div>
            </div>
            <div class="seleccionado opciones" id="cs_extra_block" ng-class="{true:'show'}[result.options.length>0]">
                <label>Дополнительные опции:</label>
                {% verbatim %}
                <div class="valor" ng-repeat="valor in result.options">{{ extra_options[valor] }}</div>
                {% endverbatim %}
            </div>
            <div class="seleccionado condiciones">
                <label>Условия оплаты и отмены бронирования:</label>
                <div class="valor">{% verbatim %}{{ payment_terms[result.terms] }}{% endverbatim %}</div>
            </div>
    </div>
    </div>


    <div class="total">
        <div class="rules_links">
            <a href="#booking_rules" class="terms_of_booking popup_link"><span class="des">{% trans "Terms of booking" %}</span></a>
            <div style="display: none;">
                 <div id="booking_rules" class="fancybox-booking">
                    <h2>Правила бронирования</h2>
                     <ul class="fancybox-list">
                         <li>При бронировании принимаются карты Visa и MasterCard<br>
Вы можете отменить бронирование не позднее чем 2 недели до заезда.</li>
                         <li>За 2 недели до заезда на вашей банковской карты, указанной при бронировании, будет заблокирована сумма первого дня проживания, которая будет списана при отмене бронирования в срок менее чем 2 недели до заезда.</li>
                         <li>Полная стоимость проживания списывается с карты при заселении. Возможен расчет наличными средствами (в этом случае, заблокированная на карте сумма будет разблокирована в срок обусловленный правилами вашего банка).</li>
                         <li>В случае незаезда списывается полная сумма забронированного проживания.</li>
                         <li>При бронировании специальных предложений и при «горячем» бронировании полная стоимость проживания списывается сразу после совершения бронирования. Отмена бронирования не допускается.</li>
                         <li>Оплатить проживание вы можете с помощью банковской карты, наличными средствами, банковским переводом.</li>
                         <li>По вопросам, связанным с бронированием и финансовыми расчетами, вы можете обращаться в клиентскую службу Booking.com или к администрации Lekotti.</li>
                     </ul>
                 </div>
             </div>
            <a href="#liability_provisions" class="popup_link"><span class="des">{% trans "liability provisions" %}</span></a>
            <div style="display: none;">
                 <div id="liability_provisions" class="fancybox-booking">
                    <h2>{% trans "liability provisions" %}</h2>
                     <ul class="fancybox-list">
                         <li>Здесь текст.</li>
                         <li>Текст об условиях ответственности</li>
                         <li>Нужно его будет написать.</li>
                     </ul>
                 </div>
             </div>
        </div>
        <div class="adaptabilidad_promedio">
            <div class="all_costs">
                <div class="total_cost">
                    <label>{% trans "full cost<br>of accommodation:" %}</label>
                    <div class="cost_number"><span id="full_cost">0</span> €</div>
                    <input type="hidden" name="price" value="0">
                </div>
                <div class="now_cost">
                    <label>{% trans "Current<br>Amount payment:" %}</label>
                    <div class="cost_number"><span id="now_cost">0</span> €</div>
                </div>
            </div>
            <button type="submit" class="btn btn-lg btn-primary booking">{% trans "book" context "Form submit" %}</button>
        </div>
    </div>
    </form>
    </div>
    </div>


{% endblock %}
{% block extra_js %}
    <script src="{% static "js/booking2.js" %}"></script>
    {% with "js/moment/"|add:LANGUAGE_CODE|add:".js" as langFile %}
    <script src="{% static langFile %}"></script>
    <script>
    window['config'] = {
        'lang': '{{ LANGUAGE_CODE }}',
        'acc_types': {
{% for type in types %}
            {{ type.id }}: {
                'id': {{ type.id }},
                'name': '{{ type.name }}',
                'photo': '{{ type.photo }}',
                'description': '{{ type.description|escapejs }}',
                'object_number': {{ type.object_number }},
                'guests_number': {{ type.guests_number }},
                'adults_number': {{ type.adults_number }}
            }{% if not forloop.last %},{% endif %}
{% endfor %}
        },
        'extra_options': {
{% for option in options %}
            {{ option.id }}: '{{ option.name }}'{% if not forloop.last %},{% endif %}
{% endfor %}
        },
        'payment_terms': {
{% for option in payment_terms %}
           {{ option.id }}: '{{ option.name }}'{% if not forloop.last %},{% endif %}
{% endfor %}
        }
    };
    </script>
    {% endwith %}
    {% with "js/jqueryui/i18n/jquery.ui.datepicker-"|add:LANGUAGE_CODE|add:".js" as langFile %}
    <script src="{% static langFile %}"></script>
    {% endwith %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
{% endblock %}

booking/templates/booking/booking_base.html
{% extends "base.html" %}

booking/templates/booking/booking_cancel.html
{% extends "booking/booking_base.html" %}
{% load staticfiles i18n %}
{% block content %}
    <div class="container booking">
    <form method="post" action="{% url "booking:cancel" order.id order.get_public_key %}">
        {% csrf_token %}
        <h2>{% trans "Order # " %}{{ order.id }}</h2>
        {{ form }}
        <button type="submit" class="btn btn-primary btn-lg">{% trans "Cancel" %}</button>
    </form>
    </div>
{% endblock %}

booking/templates/booking/booking_success.html
{% extends "booking/booking_base.html" %}
{% load staticfiles i18n %}
{% block content %}

    <div class="container booking">
    Ваша заявка № {{ order.id }} принята!
    <br><br>
    <form action="https://payment.paytrail.com/" method="post">
        <input name="MERCHANT_ID" type="hidden" value="{{ MERCHANT_ID }}" />
        <input name="AMOUNT" type="hidden" value="{{ PAYMENT_AMOUNT }}" />
        <input name="ORDER_NUMBER" type="hidden" value="{{ ORDER_NUMBER }}" />
        <input name="CURRENCY" type="hidden" value="EUR" />
        <input name="RETURN_ADDRESS" type="hidden" value="{{ return_address }}" />
        <input name="CANCEL_ADDRESS" type="hidden" value="{{ return_address }}" />
        <input name="NOTIFY_ADDRESS" type="hidden" value="{{ return_address }}" />
        <input name="TYPE" type="hidden" value="S1" />
        <input name="CULTURE" type="hidden" value="en_US">
        <input name="MODE" type="hidden" value="1">
        <input name="AUTHCODE" type="hidden" value="{{ AUTHCODE }}" />
        <input name="submit" type="submit" class="btn btn-primary btn-lg" value="{% trans "Pay" %}" />
    </form>
    </div>
{% endblock %}