events/urls.py
from django.conf.urls import patterns, url
from .views import EventDetailView

urlpatterns = patterns('',
                       url(r'^$', 'events.views.home', name='home'),
                       url(r'^(?P<code>promotions)/$', 'events.views.event_filter', name='event_filter'),
                       url(r'^(?P<code>regional)/$', 'events.views.event_filter', name='event_filter'),
                       url(r'^(?P<code>past)/$', 'events.views.event_filter', name='event_filter'),
                       url(r'^(?P<slug>\w+)/$', EventDetailView.as_view(), name='detail'),
                       )

lekotti/urls.py
from lekotti import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from .sitemap import sitemaps
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
admin.autodiscover()

import object_tools
object_tools.autodiscover()


urlpatterns = i18n_patterns('',
                            url(r'^gallery/', include('gallery.urls', namespace='gallery')),
                            url(r'^booking/', include('booking.urls', namespace='booking')),
                            url(r'^activity/', include('activity.urls', namespace='activity')),
                            url(r'^interesting/', include('interesting.urls', namespace='interesting')),
                            url(r'^services/', include('services.urls', namespace='services')),
                            url(r'^events/', include('events.urls', namespace='events')),
                            url(r'^ski_slope/worktime/', 'skislope.views.worktime', name='ski_slope_worktime'),
                            url(r'^bus_schedule/(?P<month>\d{2})/(?P<day>\d{2})/(?P<year>\d{4})/',
                                'contact.views.bus_schedule', name='bus_schedule'),
                            url(r'^admin/help/', include('admin_help.urls', namespace='help')),
                            )


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^admin/translate/', include('rosetta.urls')),
                            )


urlpatterns += patterns('',
                        url(r'^admin_tools/', include('admin_tools.urls')),
                        url(r'^cked/', include('cked.urls')),
                        url(r'^lang/(?P<code>[a-z]{2})/$', 'main.views.lang', name='lang'),
                        url(r'^accounts/profile/', 'main.views.login_success'),
                        url(r'^accounts/', include('allauth.urls')),
                        # url(r'^accounts/profile/', RedirectView.as_view(url='/')),
                        url(r'^logout/', 'main.views.user_logout', name='logout'),
                        # url(r'', include('social_auth.urls')),
                        )
urlpatterns += i18n_patterns('',
                             url(r'^admin/', include(admin.site.urls)),
                             )


urlpatterns += patterns('',
                        (r'^%s(.*)$' % settings.STATIC_URL[1:],
                         'django.views.static.serve',
                         {'document_root': settings.STATIC_ROOT}),
                        )
urlpatterns += patterns('',
                        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve',
                         {"document_root": settings.MEDIA_ROOT}),
                        )


if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^404/$', TemplateView.as_view(template_name='404.html')),
                            url(r'^500/$', TemplateView.as_view(template_name='500.html')),
                            )


urlpatterns += patterns('',
                        url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
                        url(r'^robots\.txt$', 'main.views.robots')
                        )

urlpatterns += i18n_patterns('',
                             (r'^(?P<url>.*)$', 'main.views.extend_flatpage'),
                             )

urlpatterns += patterns('',
                        (r'^object-tools/', include(object_tools.tools.urls)),
                        )

skislope/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from tablefield.fields import TableField
from cked.fields import RichTextField
from sorl.thumbnail import ImageField, get_thumbnail
import datetime
from django_resized import ResizedImageField
from django.core.exceptions import ValidationError
from django.db.models import Q


class PriceList(models.Model):
    name = models.CharField(_('title'), max_length=256, blank=True, null=True)
    code = models.SlugField(_('slug'), max_length=32, help_text=_('for use in templates'))
    table_data = TableField(_('table'),
                            help_text=_('Click on cell to edit, right-click to ad or remove columns and rows.<br>'
                                        'First row contains table header'))

    def __unicode__(self):
        return u'%s [%s]' % (self.name, self.code)

    class Meta:
        verbose_name = _('price list')
        verbose_name_plural = _('price lists')
        ordering = ['name']


class ActualScheduleManager(models.Manager):
    def get_query_set(self):
        today = datetime.date.today()
        return super(ActualScheduleManager, self).get_query_set().filter(active_from__lte=today, active_to__gte=today)


class ActiveScheduleManager(models.Manager):
    def get_query_set(self):
        return super(ActiveScheduleManager, self).get_query_set().filter(active=True)


class Schedule(models.Model):
    active_from = models.DateField(_('active from'))
    active_to = models.DateField(_('active to'))
    description = RichTextField(_('description'), null=True, blank=True)
    active = models.BooleanField(_('active'), default=True)

    objects = models.Manager()
    actual = ActualScheduleManager()
    active_objects = ActiveScheduleManager()

    def __unicode__(self):
        return u'%s %s %s %s' % (_('from'), self.active_from, _('to'), self.active_to)

    class Meta:
        ordering = ['-active_from']
        verbose_name = _('schedule')
        verbose_name_plural = _('schedules')

    def clean(self):
        if self.active_from > self.active_to:
            raise ValidationError(_('possible dates are reversed?'))
        existing_schedules = Schedule.objects.exclude(id=self.id)
        for sch in existing_schedules:
            if sch.active_from <= self.active_from <= sch.active_to or \
                                    sch.active_from <= self.active_to <= sch.active_to:
                raise ValidationError(_('dates are crossing other schedule: %s') % sch)


class WorkTime(models.Model):
    WEEKDAY_CHOICES = (
        (0, _('monday')),
        (1, _('tuesday')),
        (2, _('wednesday')),
        (3, _('thursday')),
        (4, _('friday')),
        (5, _('saturday')),
        (6, _('sunday')),
    )
    weekday = models.PositiveSmallIntegerField(_('day of the week'), choices=WEEKDAY_CHOICES)
    active = models.BooleanField(_('workday'), default=True)
    open = models.TimeField(_('open time'), null=True, blank=True)
    close = models.TimeField(_('close time'), null=True, blank=True)
    schedule = models.ForeignKey(Schedule)

    def ancient_weekday(self):
        return datetime.date(2001, 1, self.weekday+1)

    def verbose_weekday(self):
        return datetime.date(2001, 1, self.weekday+1).strftime('%A')

    def __unicode__(self):
        return u'%s' % self.verbose_weekday()


class UpcomingRescheduleManager(models.Manager):
    def get_query_set(self):
        check_date = datetime.date.today()
        return super(UpcomingRescheduleManager, self).get_query_set().filter(
            Q(date__gte=check_date, date_end=None) | Q(date_end__gte=check_date)
        )


class Reschedule(models.Model):
    date = models.DateField(_('date'))
    date_end = models.DateField(_('end of period'), blank=True, null=True)
    holiday = models.BooleanField(_('holiday'), default=False)
    open = models.TimeField(_('open time'), null=True, blank=True)
    close = models.TimeField(_('close time'), null=True, blank=True)

    objects = models.Manager()
    upcoming = UpcomingRescheduleManager()

    def __unicode__(self):
        if self.date_end:
            s = u'%s %s %s %s' % (_('from'), self.date, _('to'), self.date_end)
        else:
            s = u'%s' % self.date
        return s

    class Meta:
        ordering = ['date']
        verbose_name = _('reschedule')
        verbose_name_plural = _('reschedules')


class PriceType(models.Model):
    name = models.CharField(_('name'), max_length=26)
    slug = models.SlugField(_('slug'), null=True, blank=True)
    ordering = models.IntegerField(_('ordering'), default=100)
#     image = ImageField(_('image'), upload_to='skislope')
    image = ResizedImageField(max_width=1000, upload_to='skislope', verbose_name=_('image'))
    content = RichTextField(_('tab content'), null=True, blank=True)

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('price type')
        verbose_name_plural = _('price types')
        ordering = ['ordering']

skislope/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from .models import WorkTime, Reschedule, Schedule


def worktime(request):
    return render_to_response('skislope/schedule.html', {
        'worktime': WorkTime.objects.all(),
        'schedules': Schedule.active_objects.all(),
        'reschedule': Reschedule.upcoming.all(),
    }, context_instance=RequestContext(request))

skislope/templates/skislope/schedule.html
{% extends "base.html" %}
{% load i18n sitetree chunks staticfiles %}
{% block head_extra_css %}
    <link rel="stylesheet" href="{% static "css/print.css" %}" media="print">
{% endblock %}
{% block content_header %}
    <header class="container content-head">
        <div class="pull-right material-tools hidden-print">
            {% block content-head-tools %}
                <a class="material-tool up back2list" href="/ski_slope/">{% chunk 'sky_slope-description' %}</a>
            {% endblock %}
        </div>
        <h1 class="pull-left">{% sitetree_page_title from "maintree" %}</h1>
    </header>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
{% for schedule in schedules %}
                {{ schedule.description|safe }}
                <table class="table table-striped">
                    <thead><tr>
                        <th>{% chunk "ski_weekday" %}</th>
                        <th>{% chunk "ski_worktime" %}</th>
                    </tr></thead>
                    <tbody>
                    {% for row in schedule.worktime_set.all %}
                        <tr>
                            <td>{{ row.ancient_weekday|date:"l" }}</td>
                            <td>
                                {% if not row.active %}
                                    {% chunk "ski_dont_work" %}
                                {% else %}
                                    {% if row.open %} {% chunk "ski_from" %} {{ row.open|time:"H:i" }} {% endif %}
                                    {% if row.close %} {% chunk "ski_to" %} {{ row.close|time:"H:i" }} {% endif %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <br><br>
{% endfor %}
            {% if reschedule %}
                {% chunk "ski_slope_worktime_changes" %}
                <table class="table table-striped">
                    <thead><tr>
                        <th>{% chunk "ski_period" %}</th>
                        <th>{% chunk "ski_worktime" %}</th>
                    </tr></thead>
                    <tbody>
                    {% for row in reschedule %}
                        <tr>
                            <td>{% if row.date_end %}{% chunk "ski_from" %} {{ row.date|date:"d.m" }} {% chunk "ski_to" %} {{ row.date_end|date:"d.m" }}{% else %}
                                {{ row.date|date:"d.m" }}{% endif %}
                            </td>
                            <td>
                                {% if row.holiday %}
                                    {% chunk "ski_dont_work" %}
                                {% else %}
                                    {% if row.date_end %}{% if row.open or row.close %}{% chunk "ski_every-day" %}{% endif %}{% endif %}
                                    {% if row.open %} {% chunk "ski_from" %} {{ row.open|time:"H:i" }} {% endif %}
                                    {% if row.close %} {% chunk "ski_to" %} {{ row.close|time:"H:i" }} {% endif %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            <div class="row rc_save hidden-print">
                <div class="col-md-3"><a href="javascript:window.print()" class="printing">{% chunk "ski_print" %}</a></div>
                <div class="col-md-9"><a href="javascript:location.href='mailto:?SUBJECT='+document.title+'&BODY='+escape(location.href)" class="send_link">{% chunk "ski_send-link" %}</a></div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

skislope/templates/skislope/ski_price.html
{% load tables chunks i18n %}
    <section class="price_lists_data incut">
        <div class="container tab-content price_block_content">
            <div class="row tab-pane active" id="tab_tickets">
                <div class="col-md-8 price_block_content gr_block">
                    {% table price.single_visit %}<br><br>
                    {% table price.abonements 'collapsed' %}
                </div>
            </div>
            <div class="row tab-pane" id="tab_rental">
                <div class="col-md-8 gr_block">
                    {% chunk "price_equipment_before" %}
                    <br>
                    <div class="table-price">
                    {% table price.equipment_ski_adult %}
                    {% table price.equipment_ski_children %}
                    {% table price.equipment_snowboard_adult %}
                    {% table price.equipment_snowboard_children %}
                    </div>
                    <br>
                    {% chunk "price_equipment_after" %}<br>
                    <a class="how-to-get-link btn btn-primary btn-lg" href="/activity/">{% chunk "ski_activity-list" %}</a>
                </div>
            </div>
            <div class="row tab-pane" id="tab_training">
                <div class="col-md-8 price_block_content gr_block">
                    {% chunk "price_cost_before" %}
                    <br>
                    {% table price.training %}
                    <br>
                    {% chunk "price_cost_after" %}
                </div>
            </div>
        </div>
    </section>

skislope/templates/skislope/ski_price_variants.html
{% load i18n chunks thumbnail evaluate chunks %}
    <section class="section">
        <h3>{% chunk "ski_price" %}</h3>
{% if tabs %}
        <ul class="row list-unstyled">
{% for tab in tabs %}
            <li class="col-xs-4 variant-tile{% if forloop.first %} active{% endif %}">
                <a class="variant_tile" href="#tab-pane-{% if tab.slug %}{{ tab.slug }}{% else %}tab_{{ tab.id }}{% endif %}" data-toggle="tab">
{% thumbnail tab.image "230x139" as im %}
                    <img src="{{ im.url }}" class="img-responsive">
{% endthumbnail %}
                    <h4>{{ tab.name }}</h4>
                </a>
            </li>
{% endfor %}
        </ul>
    </div></div></div></div>
    <section class="price_lists_data incut">
        <div class="container tab-content price_block_content">
{% for tab in tabs %}
            <div class="row tab-pane{% if forloop.first %} active{% endif %}" id="tab-pane-{% if tab.slug %}{{ tab.slug }}{% else %}tab_{{ tab.id }}{% endif %}">
                <div class="col-md-8 price_block_content gr_block">
                    {% with content=tab.content|decode %}
                    {% evaluate content %}
                    {% endwith %}
                </div>
            </div>
{% endfor %}
        </div>
    </section>
    </section>
    <div class="container"><div class="row"><div class="col-md-8"><div>
{% endif %}

skislope/templates/skislope/worktime.html
{% load i18n chunks %}
<div class="worktime-announce">
    <hgroup class="text-center">
        <h2>{% chunk "ski_schedule" %}</h2>
        <small>{% chunk "ski_right-descr" %}</small>
    </hgroup>
    <table class="table table-compact">
        {% for row in schedule %}
            <tr class="row_{{ row.date|date:"w" }}">
                <td>
                    {% if forloop.first %}
                        {% chunk "ski_today" %}
                    {% else %}
                        {{ row.date|date:"d.m" }}
                    {% endif %}
                </td>
                <td>{{ row.date|date:"D" }}</td>
                <td>
                    {% if row.open %}{% chunk "ski_from" %} {{ row.open|time:"H:i" }}{% endif %}
                    {% if row.close %}{% chunk "ski_to" %} {{ row.close|time:"H:i" }}{% endif %}
                    {% if not row.open and not row.close %}&mdash;{% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <p><a href="{% url "ski_slope_worktime" %}" class="for_all_season">{% chunk "ski_schedule-for-all-season" %}</a></p>

</div>